name: analying_analyzer
description: Checking out how to read metadata for code generation using analyzer
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.3.1 <4.0.0"
  flutter: ">=3.19.2"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  analyzer: ^6.4.1
  get_it: ^7.6.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  source_gen: ^1.5.0
  build_runner: ^2.4.8
  package_config: ^2.1.0


flutter:
  uses-material-design: true