targets:
  $default:
    builders:
      source_gen_play:
        enabled: true
        # options:
          # build_extensions:
            # '^lib/models/{{}}.dart': 'lib/models/generated/{{}}.foo.dart'
        generate_for:
          exclude:
            - test/**
            - example/**
            - lib/**
            - bin/**
            

builders:
  source_gen_play:
    import: "package:source_gen_play/builder.dart"
    builder_factories: ["player"]
    build_extensions: { ".dart": [".player.dart"] }
    auto_apply: dependents
    build_to: source
    