name: jaspr_project
description: A basic pure-dart web app with ssr & automatic client hydration.
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^0.2.0+4

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.1
  jaspr_builder: ^0.2.0
  lints: ^2.0.1
