# Use postgres/example user/password credentials
# this helps us to bootstrap a postgres if we need to. so that we don't need to install postgres on our machine
# but I'm using postgres installed on my mahchine.
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - 5435:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080