name: download_server
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.3.1 <4.0.0'


dependencies:
  path: ^1.9.0
  mime: ^1.0.5

dev_dependencies:
  lints: ^4.0.0
